[workspace]
members = [
    "antminer",
    "bitaxe",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
digest_auth = "0.3"
mining-primitives = "0.1"
reqwest = { version = "0.12", default-features = false }
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
tokio = "1"
url = "2.5"
