//! Antminer API response types

use std::net::IpAddr;

use mining_primitives::hashrate::Hashrate;
use serde::Deserialize;

use crate::error::Error;

/// Status metadata returned by the Antminer CGI API.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ApiStatus {
    /// Single-letter status code, normally `S` for success.
    #[serde(rename = "STATUS")]
    pub status: String,
    /// Unix timestamp generated by the miner.
    pub when: u64,
    /// Short description of the response.
    #[serde(rename = "Msg")]
    pub msg: String,
    /// API version exposed by the firmware.
    pub api_version: String,
}

/// Firmware metadata included in mining API responses.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ApiInfo {
    /// Miner platform or firmware identifier.
    pub miner_version: String,
    /// Firmware compilation time.
    #[serde(rename = "CompileTime")]
    pub compile_time: String,
}

/// Miner model and firmware build information.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct MinerType {
    /// Miner model.
    pub miner_type: String,
    /// Hardware subtype identifier.
    pub subtype: String,
    /// Firmware build version.
    pub fw_version: String,
}

/// System and network information.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct SystemInfo {
    /// Network configuration mode, such as `DHCP` or `Static`.
    pub nettype: String,
    /// Active network interface.
    pub netdevice: String,
    /// Device MAC address.
    pub macaddr: String,
    /// Device hostname.
    pub hostname: String,
    /// Device IP address.
    pub ipaddress: IpAddr,
    /// Network mask.
    pub netmask: String,
    /// Configured gateway, which may be empty when using DHCP.
    pub gateway: String,
    /// Configured DNS servers, which may be empty when using DHCP.
    pub dnsservers: String,
    /// Operating system name.
    pub system_mode: String,
    /// Operating system kernel version.
    pub system_kernel_version: String,
    /// Firmware filesystem version.
    pub system_filesystem_version: String,
    /// Firmware release type.
    pub firmware_type: String,
    /// Miner serial number.
    pub serinum: String,
}

/// Unit used by an Antminer hashrate response.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum HashrateUnit {
    /// Hashes per second.
    #[serde(rename = "H/s")]
    HashesPerSecond,
    /// Kilohashes per second.
    #[serde(rename = "kH/s", alias = "KH/s")]
    KilohashesPerSecond,
    /// Megahashes per second.
    #[serde(rename = "MH/s")]
    MegahashesPerSecond,
    /// Gigahashes per second.
    #[serde(rename = "GH/s")]
    GigahashesPerSecond,
    /// Terahashes per second.
    #[serde(rename = "TH/s")]
    TerahashesPerSecond,
    /// Petahashes per second.
    #[serde(rename = "PH/s")]
    PetahashesPerSecond,
    /// Exahashes per second.
    #[serde(rename = "EH/s")]
    ExahashesPerSecond,
}

impl HashrateUnit {
    fn to_hashrate(self, value: f64) -> Result<Hashrate, Error> {
        if !value.is_finite() || value < 0.0 {
            return Err(Error::InvalidHashrate);
        }

        let multiplier = match self {
            Self::HashesPerSecond => 1.0,
            Self::KilohashesPerSecond => 1_000.0,
            Self::MegahashesPerSecond => 1_000_000.0,
            Self::GigahashesPerSecond => 1_000_000_000.0,
            Self::TerahashesPerSecond => 1_000_000_000_000.0,
            Self::PetahashesPerSecond => 1_000_000_000_000_000.0,
            Self::ExahashesPerSecond => 1_000_000_000_000_000_000.0,
        };
        let hashes_per_second = value * multiplier;

        if hashes_per_second > u64::MAX as f64 {
            return Err(Error::HashrateTooLarge);
        }

        Ok(Hashrate::from_hs(hashes_per_second as u64))
    }
}

/// Current Antminer operation mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(try_from = "u8")]
pub enum MinerMode {
    /// Normal mode.
    Normal,
    /// Sleep mode.
    Sleep,
    /// High-performance mode.
    HighPerformance,
    /// Low-power mode.
    LowPower,
}

impl TryFrom<u8> for MinerMode {
    type Error = Error;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Normal),
            1 => Ok(Self::Sleep),
            2 => Ok(Self::HighPerformance),
            3 => Ok(Self::LowPower),
            _ => Err(Error::UnknownMinerMode),
        }
    }
}

/// Detailed miner status response.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct StatsResponse {
    /// Response status.
    #[serde(rename = "STATUS")]
    pub status: ApiStatus,
    /// Firmware metadata.
    #[serde(rename = "INFO")]
    pub info: ApiInfo,
    /// Miner statistics. Current firmware returns one item.
    #[serde(rename = "STATS")]
    pub stats: Vec<MinerStats>,
}

/// Detailed miner, fan, and hashboard statistics.
#[derive(Debug, Clone, PartialEq, Deserialize)]
#[serde(try_from = "RawMinerStats")]
pub struct MinerStats {
    /// Miner uptime in seconds.
    pub elapsed: u64,
    /// Hashrate measured over the last five seconds.
    pub rate_5s: Hashrate,
    /// Hashrate measured over the last thirty minutes.
    pub rate_30m: Hashrate,
    /// Average hashrate since startup.
    pub rate_avg: Hashrate,
    /// Theoretical hashrate.
    pub rate_ideal: Hashrate,
    /// Sales hashrate.
    pub rate_sale: Hashrate,
    /// Unit used in the original response.
    pub rate_unit: HashrateUnit,
    /// Number of hashboard chains.
    pub chain_num: u64,
    /// Number of fans.
    pub fan_num: u64,
    /// Fan speeds.
    pub fan: Vec<u64>,
    /// Current operation mode.
    pub miner_mode: MinerMode,
    /// Whether dynamic frequency adjustment is active.
    pub freq_level_mode: bool,
    /// Minimum allowed frequency level.
    pub freq_level_min: u64,
    /// Current frequency level.
    pub freq_level: u64,
    /// Power consumption.
    pub watt: u64,
    /// Energy consumption per unit of hashrate.
    pub jt: f64,
    /// Ambient temperature.
    pub ambient_temp: f64,
    /// Per-hashboard statistics.
    pub chain: Vec<HashChain>,
}

#[derive(Debug, Deserialize)]
struct RawMinerStats {
    elapsed: u64,
    rate_5s: f64,
    rate_30m: f64,
    rate_avg: f64,
    rate_ideal: f64,
    rate_sale: f64,
    rate_unit: HashrateUnit,
    chain_num: u64,
    fan_num: u64,
    fan: Vec<u64>,
    #[serde(rename = "miner-mode")]
    miner_mode: MinerMode,
    #[serde(rename = "freq-level-mode")]
    frequency_level_mode: bool,
    #[serde(rename = "freq-level-min")]
    minimum_frequency_level: u64,
    #[serde(rename = "freq-level")]
    frequency_level: u64,
    watt: u64,
    jt: f64,
    ambient_temp: f64,
    chain: Vec<RawHashChain>,
}

impl TryFrom<RawMinerStats> for MinerStats {
    type Error = Error;

    fn try_from(raw: RawMinerStats) -> Result<Self, Self::Error> {
        let chain = raw
            .chain
            .into_iter()
            .map(|chain| HashChain::from_raw(chain, raw.rate_unit))
            .collect::<Result<Vec<_>, _>>()?;

        Ok(Self {
            elapsed: raw.elapsed,
            rate_5s: raw.rate_unit.to_hashrate(raw.rate_5s)?,
            rate_30m: raw.rate_unit.to_hashrate(raw.rate_30m)?,
            rate_avg: raw.rate_unit.to_hashrate(raw.rate_avg)?,
            rate_ideal: raw.rate_unit.to_hashrate(raw.rate_ideal)?,
            rate_sale: raw.rate_unit.to_hashrate(raw.rate_sale)?,
            rate_unit: raw.rate_unit,
            chain_num: raw.chain_num,
            fan_num: raw.fan_num,
            fan: raw.fan,
            miner_mode: raw.miner_mode,
            freq_level_mode: raw.frequency_level_mode,
            freq_level_min: raw.minimum_frequency_level,
            freq_level: raw.frequency_level,
            watt: raw.watt,
            jt: raw.jt,
            ambient_temp: raw.ambient_temp,
            chain,
        })
    }
}

/// Statistics for one hashboard chain.
#[derive(Debug, Clone, PartialEq)]
pub struct HashChain {
    /// Zero-based chain index.
    pub index: u64,
    /// Average chain frequency.
    pub freq_avg: u64,
    /// Theoretical chain hashrate.
    pub rate_ideal: Hashrate,
    /// Measured chain hashrate.
    pub rate_real: Hashrate,
    /// Number of ASIC chips in the chain.
    pub asic_num: u64,
    /// PIC sensor temperatures.
    pub temp_pic: Vec<i64>,
    /// PCB sensor temperatures.
    pub temp_pcb: Vec<i64>,
    /// ASIC sensor temperatures.
    pub temp_chip: Vec<i64>,
    /// Whether the hashboard EEPROM was read successfully.
    pub eeprom_loaded: bool,
    /// Hashboard serial number.
    pub sn: String,
    /// EEPROM level.
    pub eeprom_level: u64,
    /// EEPROM voltage.
    pub eeprom_vol: u64,
    /// EEPROM frequency.
    pub eeprom_freq: u64,
    /// EEPROM bin identifier.
    pub eeprom_bin: u64,
    /// EEPROM factory-test identifier.
    pub eeprom_ft: String,
    /// ASIC arrangement in the chain.
    pub tpl: Vec<Vec<u64>>,
}

impl HashChain {
    fn from_raw(raw: RawHashChain, unit: HashrateUnit) -> Result<Self, Error> {
        Ok(Self {
            index: raw.index,
            freq_avg: raw.freq_avg,
            rate_ideal: unit.to_hashrate(raw.rate_ideal)?,
            rate_real: unit.to_hashrate(raw.rate_real)?,
            asic_num: raw.asic_num,
            temp_pic: raw.temp_pic,
            temp_pcb: raw.temp_pcb,
            temp_chip: raw.temp_chip,
            eeprom_loaded: raw.eeprom_loaded,
            sn: raw.sn,
            eeprom_level: raw.eeprom_level,
            eeprom_vol: raw.eeprom_vol,
            eeprom_freq: raw.eeprom_freq,
            eeprom_bin: raw.eeprom_bin,
            eeprom_ft: raw.eeprom_ft,
            tpl: raw.tpl,
        })
    }
}

#[derive(Debug, Deserialize)]
struct RawHashChain {
    index: u64,
    freq_avg: u64,
    rate_ideal: f64,
    rate_real: f64,
    asic_num: u64,
    temp_pic: Vec<i64>,
    temp_pcb: Vec<i64>,
    temp_chip: Vec<i64>,
    eeprom_loaded: bool,
    sn: String,
    eeprom_level: u64,
    eeprom_vol: u64,
    eeprom_freq: u64,
    eeprom_bin: u64,
    eeprom_ft: String,
    tpl: Vec<Vec<u64>>,
}

/// High-level mining summary response.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct SummaryResponse {
    /// Response status.
    #[serde(rename = "STATUS")]
    pub status: ApiStatus,
    /// Firmware metadata.
    #[serde(rename = "INFO")]
    pub info: ApiInfo,
    /// Mining summary entries. Current firmware returns one item.
    #[serde(rename = "SUMMARY")]
    pub summary: Vec<MinerSummary>,
}

/// High-level mining metrics.
#[derive(Debug, Clone, PartialEq, Deserialize)]
#[serde(try_from = "RawMinerSummary")]
pub struct MinerSummary {
    /// Miner uptime in seconds.
    pub elapsed: u64,
    /// Hashrate measured over the last five seconds.
    pub rate_5s: Hashrate,
    /// Hashrate measured over the last thirty minutes.
    pub rate_30m: Hashrate,
    /// Average hashrate since startup.
    pub rate_avg: Hashrate,
    /// Theoretical hashrate.
    pub rate_ideal: Hashrate,
    /// Unit used in the original response.
    pub rate_unit: HashrateUnit,
    /// Best share difficulty submitted to a pool.
    pub bestshare: u64,
    /// Health of the miner subsystems.
    pub status: Vec<ComponentStatus>,
}

#[derive(Debug, Deserialize)]
struct RawMinerSummary {
    elapsed: u64,
    rate_5s: f64,
    rate_30m: f64,
    rate_avg: f64,
    rate_ideal: f64,
    rate_unit: HashrateUnit,
    bestshare: u64,
    status: Vec<ComponentStatus>,
}

impl TryFrom<RawMinerSummary> for MinerSummary {
    type Error = Error;

    fn try_from(raw: RawMinerSummary) -> Result<Self, Self::Error> {
        Ok(Self {
            elapsed: raw.elapsed,
            rate_5s: raw.rate_unit.to_hashrate(raw.rate_5s)?,
            rate_30m: raw.rate_unit.to_hashrate(raw.rate_30m)?,
            rate_avg: raw.rate_unit.to_hashrate(raw.rate_avg)?,
            rate_ideal: raw.rate_unit.to_hashrate(raw.rate_ideal)?,
            rate_unit: raw.rate_unit,
            bestshare: raw.bestshare,
            status: raw.status,
        })
    }
}

/// Health status for one miner subsystem.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ComponentStatus {
    /// Subsystem name, such as `rate`, `network`, `fans`, or `temp`.
    pub r#type: String,
    /// Single-letter health status, normally `s` or `e`.
    pub status: String,
    /// Firmware-specific status code.
    pub code: u64,
    /// Human-readable status message.
    pub msg: String,
}

/// Mining pool response.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct PoolsResponse {
    /// Response status.
    #[serde(rename = "STATUS")]
    pub status: ApiStatus,
    /// Firmware metadata.
    #[serde(rename = "INFO")]
    pub info: ApiInfo,
    /// Configured mining pools.
    #[serde(rename = "POOLS")]
    pub pools: Vec<Pool>,
}

/// Mining pool state and share counters.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Pool {
    /// Pool index.
    pub index: u64,
    /// Pool URL.
    pub url: String,
    /// Stratum username or worker.
    pub user: String,
    /// Connection state.
    pub status: String,
    /// Failover priority. Lower values have higher priority.
    pub priority: u64,
    /// Number of work requests.
    pub getworks: u64,
    /// Accepted shares.
    pub accepted: u64,
    /// Rejected shares.
    pub rejected: u64,
    /// Discarded shares.
    pub discarded: u64,
    /// Stale shares.
    pub stale: u64,
    /// Current pool difficulty as reported by the firmware.
    pub diff: String,
    /// Cumulative accepted share difficulty.
    pub diffa: f64,
    /// Cumulative rejected share difficulty.
    pub diffr: f64,
    /// Cumulative stale share difficulty.
    pub diffs: f64,
    /// Difficulty of the last submitted share.
    pub lsdiff: f64,
    /// Time since the last share, as reported by the firmware.
    pub lstime: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deserialize_miner_type() {
        let json = r#"{
            "miner_type":"Antminer S21+",
            "subtype":"AMLCtrl_A3HB70XXX",
            "fw_version":"Fri Apr 18 16:15:41 CST 2025"
        }"#;

        let miner_type: MinerType = serde_json::from_str(json).unwrap();

        assert_eq!(miner_type.miner_type, "Antminer S21+");
        assert_eq!(miner_type.subtype, "AMLCtrl_A3HB70XXX");
        assert_eq!(miner_type.fw_version, "Fri Apr 18 16:15:41 CST 2025");
    }

    #[test]
    fn deserialize_system_info() {
        let json = r#"{
            "nettype": "DHCP",
            "netdevice": "eth0",
            "macaddr": "02:34:DA:F1:EB:5D",
            "hostname": "Antminer",
            "ipaddress": "192.168.1.99",
            "netmask": "255.255.255.0",
            "gateway": "",
            "dnsservers": "",
            "system_mode": "GNU/Linux",
            "system_kernel_version": "Linux 4.9.113",
            "system_filesystem_version": "FD-1.5(250418-S21+)",
            "firmware_type": "Factory",
            "serinum": "JYZZG4UBEJCAH000F"
        }"#;

        let info: SystemInfo = serde_json::from_str(json).unwrap();

        assert_eq!(info.ipaddress, "192.168.1.99".parse::<IpAddr>().unwrap());
        assert_eq!(info.serinum, "JYZZG4UBEJCAH000F");
    }

    #[test]
    fn deserialize_summary_and_convert_hashrates() {
        let json = r#"{
            "STATUS": {"STATUS":"S","when":1751945786,"Msg":"summary","api_version":"1.0.0"},
            "INFO": {"miner_version":"platform[AML]","CompileTime":"Fri Apr 18 16:15:41 CST 2025"},
            "SUMMARY": [{
                "elapsed":818,
                "rate_5s":232436.76,
                "rate_30m":231431.07,
                "rate_avg":231429.72,
                "rate_ideal":232866.0,
                "rate_unit":"GH/s",
                "bestshare":0,
                "status":[{"type":"rate","status":"s","code":0,"msg":""}]
            }]
        }"#;

        let response: SummaryResponse = serde_json::from_str(json).unwrap();
        let summary = &response.summary[0];

        assert_eq!(summary.rate_5s.to_hs(), 232_436_760_000_000);
        assert_eq!(summary.rate_avg.to_hs(), 231_429_720_000_000);
        assert_eq!(summary.rate_ideal.to_hs(), 232_866_000_000_000);
        assert_eq!(summary.status[0].r#type, "rate");
    }

    #[test]
    fn deserialize_stats_and_hashboards() {
        let json = r#"{
            "STATUS": {"STATUS":"S","when":1751944531,"Msg":"stats","api_version":"1.0.0"},
            "INFO": {"miner_version":"platform[AML]","CompileTime":"Fri Apr 18 16:15:41 CST 2025"},
            "STATS": [{
                "elapsed":818,
                "rate_5s":232436.76,
                "rate_30m":231431.07,
                "rate_avg":231429.72,
                "rate_ideal":232866.0,
                "rate_sale":225000,
                "rate_unit":"GH/s",
                "chain_num":1,
                "fan_num":2,
                "fan":[4560,4530],
                "miner-mode":0,
                "freq-level-mode":false,
                "freq-level-min":50,
                "freq-level":100,
                "watt":3500,
                "jt":15.2,
                "ambient_temp":34.5,
                "chain":[{
                    "index":0,
                    "freq_avg":708,
                    "rate_ideal":77622.0,
                    "rate_real":77143.24,
                    "asic_num":55,
                    "temp_pic":[40,41],
                    "temp_pcb":[50,51],
                    "temp_chip":[65,66],
                    "eeprom_loaded":true,
                    "sn":"JYZZYT0BEJCAH002M",
                    "eeprom_level":1,
                    "eeprom_vol":1331,
                    "eeprom_freq":708,
                    "eeprom_bin":2,
                    "eeprom_ft":"F1V01B4C2",
                    "tpl":[[1,2,3,4,5],[10,9,8,7,6]]
                }]
            }]
        }"#;

        let response: StatsResponse = serde_json::from_str(json).unwrap();
        let stats = &response.stats[0];

        assert_eq!(stats.miner_mode, MinerMode::Normal);
        assert_eq!(stats.fan, vec![4560, 4530]);
        assert_eq!(stats.chain[0].rate_real.to_hs(), 77_143_240_000_000);
        assert_eq!(stats.chain[0].temp_chip, vec![65, 66]);
        assert_eq!(stats.chain[0].eeprom_vol, 1331);
        assert_eq!(stats.chain[0].tpl[0], vec![1, 2, 3, 4, 5]);
    }

    #[test]
    fn deserialize_pool() {
        let json = r#"{
            "STATUS":{"STATUS":"S","when":1751944006,"Msg":"pools","api_version":"1.0.0"},
            "INFO":{"miner_version":"platform[AML]","CompileTime":"Fri Apr 18 16:15:41 CST 2025"},
            "POOLS":[{
                "index":0,
                "url":"stratum+tcp://pool.example:3333",
                "user":"worker",
                "status":"Alive",
                "priority":0,
                "getworks":308,
                "accepted":12,
                "rejected":1,
                "discarded":0,
                "stale":0,
                "diff":"1.05M",
                "diffa":123.5,
                "diffr":1,
                "diffs":0,
                "lsdiff":64,
                "lstime":"42"
            }]
        }"#;

        let response: PoolsResponse = serde_json::from_str(json).unwrap();
        let pool = &response.pools[0];

        assert_eq!(pool.diff, "1.05M");
        assert_eq!(pool.lstime, "42");
    }

    #[test]
    fn reject_unknown_hashrate_units() {
        let json = r#"{
            "elapsed":1,
            "rate_5s":1,
            "rate_30m":1,
            "rate_avg":1,
            "rate_ideal":1,
            "rate_unit":"ZH/s",
            "bestshare":0,
            "status":[]
        }"#;

        assert!(serde_json::from_str::<MinerSummary>(json).is_err());
    }

    #[test]
    fn convert_supported_hashrate_units() {
        let cases = [
            (HashrateUnit::HashesPerSecond, 1),
            (HashrateUnit::KilohashesPerSecond, 1_000),
            (HashrateUnit::MegahashesPerSecond, 1_000_000),
            (HashrateUnit::GigahashesPerSecond, 1_000_000_000),
            (HashrateUnit::TerahashesPerSecond, 1_000_000_000_000),
            (HashrateUnit::PetahashesPerSecond, 1_000_000_000_000_000),
            (HashrateUnit::ExahashesPerSecond, 1_000_000_000_000_000_000),
        ];

        for (unit, expected) in cases {
            assert_eq!(unit.to_hashrate(1.0).unwrap().to_hs(), expected);
        }
    }

    #[test]
    fn reject_hashrate_overflow() {
        assert!(HashrateUnit::ExahashesPerSecond.to_hashrate(20.0).is_err());
    }
}
